ALTER TABLE shops ADD COLUMN IF NOT EXISTS business_type VARCHAR(60) DEFAULT 'Kirana Store';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS upi_qr_image TEXT;
UPDATE shops SET business_type = 'Kirana Store' WHERE business_type IS NULL OR business_type = '';
ALTER TABLE shops ALTER COLUMN business_type SET DEFAULT 'Kirana Store';

ALTER TABLE products ADD COLUMN IF NOT EXISTS gst_rate INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id BIGINT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS amount_paid NUMERIC(38, 2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS balance_due NUMERIC(38, 2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_cost NUMERIC(38, 2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gross_profit NUMERIC(38, 2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20);

UPDATE orders SET amount_paid = COALESCE(amount_paid, total_amount, 0) WHERE amount_paid IS NULL;
UPDATE orders SET balance_due = COALESCE(balance_due, 0) WHERE balance_due IS NULL;
UPDATE orders SET total_cost = COALESCE(total_cost, 0) WHERE total_cost IS NULL;
UPDATE orders SET gross_profit = COALESCE(gross_profit, total_amount, 0) WHERE gross_profit IS NULL;
UPDATE orders SET payment_status = CASE
    WHEN COALESCE(balance_due, 0) > 0 AND COALESCE(amount_paid, 0) > 0 THEN 'PARTIAL'
    WHEN COALESCE(balance_due, 0) > 0 THEN 'DUE'
    ELSE 'PAID'
END
WHERE payment_status IS NULL;

ALTER TABLE orders ALTER COLUMN amount_paid SET DEFAULT 0;
ALTER TABLE orders ALTER COLUMN balance_due SET DEFAULT 0;
ALTER TABLE orders ALTER COLUMN total_cost SET DEFAULT 0;
ALTER TABLE orders ALTER COLUMN gross_profit SET DEFAULT 0;

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(20),
    outstanding_balance NUMERIC(38, 2) NOT NULL DEFAULT 0,
    total_credit_extended NUMERIC(38, 2) NOT NULL DEFAULT 0,
    total_credit_recovered NUMERIC(38, 2) NOT NULL DEFAULT 0,
    last_transaction_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_shop_phone_unique
ON customers (shop_id, phone);

ALTER TABLE customers
    DROP CONSTRAINT IF EXISTS fk_customers_shop;

ALTER TABLE customers
    ADD CONSTRAINT fk_customers_shop
    FOREIGN KEY (shop_id) REFERENCES shops(id);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    order_id BIGINT,
    created_by_user_id BIGINT,
    entry_type VARCHAR(20) NOT NULL,
    amount NUMERIC(38, 2) NOT NULL,
    balance_after NUMERIC(38, 2) NOT NULL,
    note VARCHAR(255),
    direction VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

ALTER TABLE ledger_entries
    DROP CONSTRAINT IF EXISTS fk_ledger_entries_shop;

ALTER TABLE ledger_entries
    ADD CONSTRAINT fk_ledger_entries_shop
    FOREIGN KEY (shop_id) REFERENCES shops(id);

ALTER TABLE ledger_entries
    DROP CONSTRAINT IF EXISTS fk_ledger_entries_customer;

ALTER TABLE ledger_entries
    ADD CONSTRAINT fk_ledger_entries_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id);

ALTER TABLE ledger_entries
    DROP CONSTRAINT IF EXISTS fk_ledger_entries_order;

ALTER TABLE ledger_entries
    ADD CONSTRAINT fk_ledger_entries_order
    FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE ledger_entries
    DROP CONSTRAINT IF EXISTS fk_ledger_entries_user;

ALTER TABLE ledger_entries
    ADD CONSTRAINT fk_ledger_entries_user
    FOREIGN KEY (created_by_user_id) REFERENCES users(id);

ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS fk_orders_customer;

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id);

-- ============================================================
-- BizKart Enhanced: Customer Portal Tables
-- ============================================================

CREATE TABLE IF NOT EXISTS customer_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    phone         VARCHAR(20)  NOT NULL UNIQUE,
    email         VARCHAR(120),
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_accounts_phone
    ON customer_accounts(phone);

CREATE TABLE IF NOT EXISTS delivery_addresses (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_account_id BIGINT NOT NULL,
    label               VARCHAR(40)  DEFAULT 'Home',
    line1               VARCHAR(200) NOT NULL,
    line2               VARCHAR(200),
    city                VARCHAR(80)  NOT NULL,
    state               VARCHAR(80)  DEFAULT 'Telangana',
    pincode             VARCHAR(10)  NOT NULL,
    landmark            VARCHAR(120),
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP,
    CONSTRAINT fk_da_customer FOREIGN KEY (customer_account_id)
        REFERENCES customer_accounts(id)
);

CREATE TABLE IF NOT EXISTS online_orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number         VARCHAR(60) NOT NULL UNIQUE,
    shop_id              BIGINT NOT NULL,
    customer_account_id  BIGINT NOT NULL,
    order_type           VARCHAR(20) NOT NULL CHECK (order_type IN ('DELIVERY','PICKUP')),
    delivery_address_id  BIGINT,
    delivery_address_text TEXT,
    subtotal             NUMERIC(38,2) NOT NULL DEFAULT 0,
    delivery_fee         NUMERIC(38,2) NOT NULL DEFAULT 0,
    discount             NUMERIC(38,2) NOT NULL DEFAULT 0,
    total_amount         NUMERIC(38,2) NOT NULL,
    payment_method       VARCHAR(20) NOT NULL CHECK (payment_method IN ('COD','UPI','CARD')),
    payment_status       VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                         CHECK (payment_status IN ('PENDING','PAID','FAILED','REFUNDED')),
    payment_reference    VARCHAR(120),
    status               VARCHAR(30) NOT NULL DEFAULT 'PLACED'
                         CHECK (status IN ('PLACED','CONFIRMED','PREPARING','READY',
                                           'OUT_FOR_DELIVERY','DELIVERED','PICKED_UP',
                                           'CANCELLED','REFUNDED')),
    cancellation_reason  TEXT,
    assigned_to_user_id  BIGINT,
    estimated_ready_at   TIMESTAMP,
    delivered_at         TIMESTAMP,
    customer_notes       TEXT,
    internal_notes       TEXT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    CONSTRAINT fk_oo_shop     FOREIGN KEY (shop_id)             REFERENCES shops(id),
    CONSTRAINT fk_oo_customer FOREIGN KEY (customer_account_id) REFERENCES customer_accounts(id),
    CONSTRAINT fk_oo_address  FOREIGN KEY (delivery_address_id) REFERENCES delivery_addresses(id),
    CONSTRAINT fk_oo_staff    FOREIGN KEY (assigned_to_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_oo_shop_status ON online_orders(shop_id, status);
CREATE INDEX IF NOT EXISTS idx_oo_customer    ON online_orders(customer_account_id);
CREATE INDEX IF NOT EXISTS idx_oo_created     ON online_orders(created_at);

CREATE TABLE IF NOT EXISTS online_order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    online_order_id BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    product_name    VARCHAR(200) NOT NULL,
    unit_price      NUMERIC(38,2) NOT NULL,
    quantity        INTEGER NOT NULL CHECK (quantity > 0),
    subtotal        NUMERIC(38,2) NOT NULL,
    CONSTRAINT fk_ooi_order   FOREIGN KEY (online_order_id) REFERENCES online_orders(id),
    CONSTRAINT fk_ooi_product FOREIGN KEY (product_id)      REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS online_order_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    online_order_id BIGINT NOT NULL,
    status          VARCHAR(30) NOT NULL,
    changed_by_user_id BIGINT,
    note            TEXT,
    created_at      TIMESTAMP,
    CONSTRAINT fk_oosh_order FOREIGN KEY (online_order_id)    REFERENCES online_orders(id),
    CONSTRAINT fk_oosh_user  FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);

-- ============================================================
-- Phase 1: Customer Acquisition Features
-- ============================================================

-- Location fields for shops
ALTER TABLE shops ADD COLUMN IF NOT EXISTS latitude  DOUBLE PRECISION;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

-- Loyalty points on customer accounts
ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS loyalty_points INTEGER NOT NULL DEFAULT 0;

-- Coupon / discount fields on online orders
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS coupon_code          VARCHAR(60);
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS coupon_discount       NUMERIC(38,2) NOT NULL DEFAULT 0;
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS loyalty_points_used   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS loyalty_points_earned INTEGER NOT NULL DEFAULT 0;

-- Coupons table
CREATE TABLE IF NOT EXISTS coupons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id         BIGINT,                          -- NULL = platform-wide
    code            VARCHAR(60) NOT NULL UNIQUE,
    description     VARCHAR(255),
    discount_type   VARCHAR(20) NOT NULL DEFAULT 'PERCENT'
                    CHECK (discount_type IN ('PERCENT','FLAT')),
    discount_value  NUMERIC(38,2) NOT NULL,
    min_order_value NUMERIC(38,2) NOT NULL DEFAULT 0,
    max_discount    NUMERIC(38,2),                   -- cap for PERCENT type
    usage_limit     INTEGER,                          -- NULL = unlimited
    used_count      INTEGER NOT NULL DEFAULT 0,
    first_order_only BOOLEAN NOT NULL DEFAULT FALSE,
    valid_from      TIMESTAMP,
    valid_until     TIMESTAMP,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP,
    CONSTRAINT fk_coupon_shop FOREIGN KEY (shop_id) REFERENCES shops(id)
);

CREATE INDEX IF NOT EXISTS idx_coupons_code   ON coupons(code);
CREATE INDEX IF NOT EXISTS idx_coupons_active ON coupons(active);

-- Reviews table (for products & shops)
CREATE TABLE IF NOT EXISTS reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_account_id BIGINT NOT NULL,
    online_order_id     BIGINT NOT NULL,
    shop_id             BIGINT NOT NULL,
    product_id          BIGINT,               -- NULL = shop review
    rating              SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment             TEXT,
    created_at          TIMESTAMP,
    CONSTRAINT fk_review_customer FOREIGN KEY (customer_account_id) REFERENCES customer_accounts(id),
    CONSTRAINT fk_review_order    FOREIGN KEY (online_order_id)     REFERENCES online_orders(id),
    CONSTRAINT fk_review_shop     FOREIGN KEY (shop_id)             REFERENCES shops(id),
    CONSTRAINT fk_review_product  FOREIGN KEY (product_id)          REFERENCES products(id),
    CONSTRAINT uq_review_order_product UNIQUE (online_order_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_shop    ON reviews(shop_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews(product_id);

-- Web Push subscriptions
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_account_id BIGINT NOT NULL,
    endpoint            TEXT NOT NULL UNIQUE,
    p256dh              TEXT NOT NULL,
    auth                TEXT NOT NULL,
    created_at          TIMESTAMP,
    CONSTRAINT fk_push_customer FOREIGN KEY (customer_account_id) REFERENCES customer_accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_push_customer ON push_subscriptions(customer_account_id);

-- ============================================================
-- Phase 2: Retention & Experience Features
-- ============================================================

-- Live Delivery Map: agent location on order
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS agent_latitude  DOUBLE PRECISION;
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS agent_longitude DOUBLE PRECISION;
ALTER TABLE online_orders ADD COLUMN IF NOT EXISTS agent_updated_at TIMESTAMP;

-- Scheduled Orders
CREATE TABLE IF NOT EXISTS scheduled_orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_account_id BIGINT NOT NULL,
    shop_id             BIGINT NOT NULL,
    frequency           VARCHAR(20) NOT NULL CHECK (frequency IN ('DAILY','WEEKLY')),
    day_of_week         SMALLINT,               -- 1=Mon..7=Sun, NULL for DAILY
    delivery_time       VARCHAR(5) NOT NULL,    -- HH:mm
    order_type          VARCHAR(20) NOT NULL CHECK (order_type IN ('DELIVERY','PICKUP')),
    delivery_address_id BIGINT,
    items_json          TEXT NOT NULL,          -- JSON array [{productId, quantity}]
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    last_run_at         TIMESTAMP,
    next_run_at         TIMESTAMP,
    created_at          TIMESTAMP,
    CONSTRAINT fk_so_customer FOREIGN KEY (customer_account_id) REFERENCES customer_accounts(id),
    CONSTRAINT fk_so_shop     FOREIGN KEY (shop_id)             REFERENCES shops(id),
    CONSTRAINT fk_so_address  FOREIGN KEY (delivery_address_id) REFERENCES delivery_addresses(id)
);

CREATE INDEX IF NOT EXISTS idx_so_customer ON scheduled_orders(customer_account_id);
CREATE INDEX IF NOT EXISTS idx_so_next_run ON scheduled_orders(next_run_at, active);

-- In-App Chat: messages per order
CREATE TABLE IF NOT EXISTS order_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    online_order_id BIGINT NOT NULL,
    sender_type     VARCHAR(20) NOT NULL CHECK (sender_type IN ('CUSTOMER','SHOP')),
    sender_id       BIGINT NOT NULL,
    message         TEXT NOT NULL,
    created_at      TIMESTAMP,
    CONSTRAINT fk_om_order FOREIGN KEY (online_order_id) REFERENCES online_orders(id)
);

CREATE INDEX IF NOT EXISTS idx_om_order ON order_messages(online_order_id, created_at);

-- ============================================================
-- Phase 3: Growth & Analytics Features
-- ============================================================

-- Referral Program
ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS referral_code VARCHAR(20) UNIQUE;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS public_slug VARCHAR(80) UNIQUE;

CREATE TABLE IF NOT EXISTS referrals (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_customer_id    BIGINT NOT NULL,
    referred_customer_id    BIGINT NOT NULL UNIQUE,
    coupon_code_referrer    VARCHAR(60),
    coupon_code_referred    VARCHAR(60),
    completed               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP,
    completed_at            TIMESTAMP,
    CONSTRAINT fk_ref_referrer  FOREIGN KEY (referrer_customer_id) REFERENCES customer_accounts(id),
    CONSTRAINT fk_ref_referred  FOREIGN KEY (referred_customer_id) REFERENCES customer_accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_customer_id);

-- SMS Marketing campaigns
CREATE TABLE IF NOT EXISTS sms_campaigns (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    message      TEXT NOT NULL,
    target_type  VARCHAR(30) NOT NULL DEFAULT 'ALL'
                 CHECK (target_type IN ('ALL','ACTIVE','INACTIVE','HIGH_VALUE')),
    shop_id      BIGINT,
    status       VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                 CHECK (status IN ('DRAFT','SENT','SCHEDULED')),
    recipient_count INTEGER NOT NULL DEFAULT 0,
    scheduled_at TIMESTAMP,
    sent_at      TIMESTAMP,
    created_at   TIMESTAMP,
    CONSTRAINT fk_sms_shop FOREIGN KEY (shop_id) REFERENCES shops(id)
);

CREATE INDEX IF NOT EXISTS idx_sms_campaigns_status ON sms_campaigns(status);
